spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:13306/urlshortener?useSSL=false
    username: urlshortener
    password: "usus12!@"
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    favicon:
      enabled: false
  main:
    banner-mode: 'OFF'

logging:
  level:
    com.peterminhk.app.urlshortener: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
